import "./globals.css";
import Navbar from "./Navbar";
import Footer from "./Footer";
import { Poppins, Inter } from "next/font/google";
import BottomTabBar from "./components/home/TabBar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable} antialiased`}>
          <Navbar />
          {children}
          <Footer />
        <BottomTabBar />
      </body>
    </html>
  );
}